# Generated by Django 4.0.1 on 2022-01-24 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autheri1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='service',
            new_name='person_user',
        ),
    ]
