# Generated by Django 4.0.1 on 2022-01-25 05:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('autheri1', '0003_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person_user',
            old_name='service_icon',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='person_user',
            old_name='service_title',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='person_user',
            name='id',
        ),
        migrations.RemoveField(
            model_name='person_user',
            name='service_description',
        ),
        migrations.AddField(
            model_name='person_user',
            name='ID',
            field=models.AutoField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='person_user',
            name='email',
            field=models.EmailField(blank=True, max_length=70, unique=True),
        ),
        migrations.AddField(
            model_name='person_user',
            name='rollnumber',
            field=models.IntegerField(blank=True, default=uuid.uuid4, unique=True),
        ),
    ]
