# Generated by Django 4.0.1 on 2022-01-25 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autheri1', '0005_remove_person_user_id_person_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person_user',
            old_name='name',
            new_name='name_one',
        ),
    ]
