# Generated by Django 4.0.1 on 2022-01-25 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autheri1', '0006_rename_name_person_user_name_one'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person_user',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='email address'),
        ),
    ]
