# Generated by Django 4.0.1 on 2022-01-25 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autheri1', '0008_delete_person_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='person_name',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='room',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
